-- 0. CREACIÓN DE TIPOS ENUMERADOS
-- En PostgreSQL, los ENUM deben declararse como tipos independientes antes de usarlos.
CREATE TYPE user_rol AS ENUM ('administrador', 'docente');
CREATE TYPE general_estado AS ENUM ('activo', 'inactivo');
CREATE TYPE dias_semana AS ENUM ('Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo');
CREATE TYPE estado_horario AS ENUM ('borrador', 'publicado');

-- 1. CONFIGURACIÓN INICIAL Y USUARIOS
CREATE TABLE usuarios (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL UNIQUE,
    cedula VARCHAR(20) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    rol user_rol NOT NULL,
    estado general_estado DEFAULT 'activo'
);

CREATE TABLE docentes (
    id_docente INT PRIMARY KEY,
    especialidad VARCHAR(100),
    FOREIGN KEY (id_docente) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE periodos (
    id_periodo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    ano_lectivo INT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    es_activo BOOLEAN DEFAULT FALSE,
    CHECK (fecha_inicio < fecha_fin)
);

-- 2. CATÁLOGOS PRINCIPALES
CREATE TABLE carreras (
    id_carrera INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE asignaturas (
    id_asignatura INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    id_carrera INT NOT NULL,
    ano_estudio INT NOT NULL,
    horas_teoricas INT NOT NULL CHECK (horas_teoricas >= 0),
    horas_practicas INT NOT NULL CHECK (horas_practicas >= 0),
    estado general_estado DEFAULT 'activo',
    FOREIGN KEY (id_carrera) REFERENCES carreras(id_carrera)
);

CREATE TABLE pabellones (
    id_pabellon INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE aulas (
    id_aula INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    id_pabellon INT NOT NULL,
    capacidad INT NOT NULL CHECK (capacidad > 0),
    estado general_estado DEFAULT 'activo',
    FOREIGN KEY (id_pabellon) REFERENCES pabellones(id_pabellon),
    UNIQUE (codigo, id_pabellon)
);

-- 3. RECURSOS Y SECCIONES
CREATE TABLE recursos (
    id_recurso INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE aula_recurso (
    id_aula INT NOT NULL,
    id_recurso INT NOT NULL,
    PRIMARY KEY (id_aula, id_recurso),
    FOREIGN KEY (id_aula) REFERENCES aulas(id_aula) ON DELETE CASCADE,
    FOREIGN KEY (id_recurso) REFERENCES recursos(id_recurso) ON DELETE CASCADE
);

CREATE TABLE secciones (
    id_seccion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_periodo INT NOT NULL,
    codigo VARCHAR(20) NOT NULL,
    id_carrera INT NOT NULL,
    ano_estudio INT NOT NULL,
    cantidad_estudiantes INT NOT NULL CHECK (cantidad_estudiantes > 0),
    FOREIGN KEY (id_periodo) REFERENCES periodos(id_periodo),
    FOREIGN KEY (id_carrera) REFERENCES carreras(id_carrera)
);

CREATE TABLE seccion_asignatura (
    id_seccion INT NOT NULL,
    id_asignatura INT NOT NULL,
    PRIMARY KEY (id_seccion, id_asignatura),
    FOREIGN KEY (id_seccion) REFERENCES secciones(id_seccion) ON DELETE CASCADE,
    FOREIGN KEY (id_asignatura) REFERENCES asignaturas(id_asignatura) ON DELETE CASCADE
);

-- 4. PLANIFICACIÓN
CREATE TABLE bloques_clase (
    id_bloque INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_periodo INT NOT NULL,
    dia dias_semana NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    es_receso BOOLEAN DEFAULT FALSE,
    CHECK (hora_inicio < hora_fin),
    FOREIGN KEY (id_periodo) REFERENCES periodos(id_periodo) ON DELETE CASCADE
);

CREATE TABLE disponibilidad_docente (
    id_disponibilidad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_docente INT NOT NULL,
    id_periodo INT NOT NULL,
    dia dias_semana NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    CHECK (hora_inicio < hora_fin),
    FOREIGN KEY (id_docente) REFERENCES docentes(id_docente) ON DELETE CASCADE,
    FOREIGN KEY (id_periodo) REFERENCES periodos(id_periodo) ON DELETE CASCADE
);

CREATE TABLE horarios (
    id_horario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_docente INT NOT NULL,
    id_asignatura INT NOT NULL,
    id_seccion INT NOT NULL,
    id_aula INT NOT NULL,
    id_bloque INT NOT NULL,
    estado_publicacion estado_horario DEFAULT 'borrador',
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_docente) REFERENCES docentes(id_docente),
    FOREIGN KEY (id_asignatura) REFERENCES asignaturas(id_asignatura),
    FOREIGN KEY (id_seccion) REFERENCES secciones(id_seccion),
    FOREIGN KEY (id_aula) REFERENCES aulas(id_aula),
    FOREIGN KEY (id_bloque) REFERENCES bloques_clase(id_bloque)
);